import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CartCounter from "./components/CartCounter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
   <html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
    <body
  className={`${geistSans.variable} ${geistMono.variable} antialiased`}
>

<div
 style={{
  display: "flex",
  justifyContent: "space-between",
  alignItems: "center",
  padding: "16px 20px",
  borderBottom: "1px solid #333",
  background: "#111",   // 👈 ADD THIS
  color: "#fff"         // 👈 ADD THIS
}}
>

  {/* LEFT */}
 <div style={{ fontWeight: "bold", fontSize: "18px", color: "#fff" }}>
    Middelburg Bearings
  </div>

  {/* RIGHT */}
  <div style={{ display: "flex", alignItems: "center", gap: "15px" }}>

    {/* Desktop menu only */}
    <div className="desktop-menu">
      <a href="/" style={{ marginRight: "15px", color: "#fff" }}>Home</a>
     <a href="/" style={{ marginRight: "15px", color: "#fff" }}>Home</a> 
    </div>

    {/* Quote Cart */}
    <a
      href="/cart"
      style={{
        background: "#2563eb",
        color: "white",
        padding: "8px 14px",
        borderRadius: "6px",
        textDecoration: "none",
        whiteSpace: "nowrap"
      }}
    >
      <CartCounter />
    </a>

  </div>

</div>


  <div style={{ padding: "20px" }}>
    {children}
  </div>

</body> 
    </html>
  );
}
